version: "3.9"

services:
  nats:
    image: nats:latest
    entrypoint: /nats-server
    command: "-c /config/server.conf"
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - ./nats/data:/data
      - ./nats/config:/config

  nats-nui:
    image: ghcr.io/nats-nui/nui:latest
    container_name: nats_nui
    ports:
      - "31311:31311"
    volumes:
      - ./nui/db:/db
    depends_on:
      - nats

  bot:
    build: .
    container_name: my_bot
    depends_on:
      - nats