"""changed tests model

Revision ID: 61edd98378f4
Revises: edcc8a08b5f0
Create Date: 2025-08-09 14:17:13.027212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61edd98378f4'
down_revision: Union[str, Sequence[str], None] = 'edcc8a08b5f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('public_folder_id', sa.String(), nullable=False))
    op.add_column('tests', sa.Column('private_folder_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tests', 'private_folder_id')
    op.drop_column('tests', 'public_folder_id')
    # ### end Alembic commands ###
