"""added sub to notifications for lessons

Revision ID: 696e922638b1
Revises: 61edd98378f4
Create Date: 2025-08-21 20:35:46.173185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '696e922638b1'
down_revision: Union[str, Sequence[str], None] = '61edd98378f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('lesson_sub', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'lesson_sub')
    # ### end Alembic commands ###
