"""added sub to notifications for deadlines

Revision ID: e82058b53489
Revises: 696e922638b1
Create Date: 2025-08-23 11:44:51.015867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e82058b53489'
down_revision: Union[str, Sequence[str], None] = '696e922638b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('deadlines_sub', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'deadlines_sub')
    # ### end Alembic commands ###
