"""changed courses_and_classes model

Revision ID: edcc8a08b5f0
Revises: 5ed324498436
Create Date: 2025-08-08 14:05:13.670118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edcc8a08b5f0'
down_revision: Union[str, Sequence[str], None] = '5ed324498436'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses_and_classes', sa.Column('folder_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses_and_classes', 'folder_id')
    # ### end Alembic commands ###
